### ISSUE TITLE
Composer pack handler error

### ISSUE THREAD

**Issue by myCodebox** [juanantoniodelgado/StopWords#11]
The library (1.3), via composer, has a lost `s` in Indonesian JSON.

`composer require juanantoniodelgado/stopwords`

In this file on Line 3 - `\src\words\indonesian.json`
```json
{
    "name": "Indonesian",
    "handler": [
        "indonesian",
        "ind",
        "id"
    ],
    "words": [
        "ada",
        "adanya",
        "adalah",
        ...
```

**Comment by myCodebox** [comment]
Sorry haven't seen this here [fda0f19](https://github.com/juanantoniodelgado/StopWords/commit/fda0f19c697d6f5993245816f71585923a391f77)

**Comment by juanantoniodelgado** [comment]
Fixed on https://github.com/juanantoniodelgado/StopWords/issues/14.

Thank you for your support and apologies for the delay.
