### ISSUE TITLE
Parse error: syntax error, unexpected token "/", expecting "," or ";" i

### ISSUE THREAD

**Issue by seodevse** [juanantoniodelgado/StopWords#12]
error: 
Parse error: syntax error, unexpected token "/", expecting "," or ";" in.....

From example code: 
use StopWords/StopWords;

$stopwords = new StopWords('en');
$stopwords->clean('your text to clean');

should be? Notice \ not /
use StopWords\StopWords;

$stopwords = new StopWords('en');
$cleanedText = $stopwords->clean('your text to clean');

**Comment by AlexNodex** [comment]
https://github.com/juanantoniodelgado/StopWords/pull/13/commits/c4fc71879fcd68410e5f978f837dd92cf2ad1a72

**Comment by juanantoniodelgado** [comment]
As @AlexNodex, the README example has a typo on its use. Simply change `use StopWords/StopWords;` with `use StopWords\StopWords;` while we are done with https://github.com/juanantoniodelgado/StopWords/pull/13.

Thank you two for your support!
